In [6]:
import tensorflow as tf

In [11]:
a = tf.constant(10,dtype='float64')
b = tf.constant(100,dtype='float64')

In [13]:
#声明算法
#乘法的任务
mul = tf.multiply(a,b)

#除法任务
div = tf.divide(b,a)

add = tf.add(mul,div)

sub = tf.subtract(1024,512)

#执行任务Session
with tf.Session() as sess:
    print(sess.run(mul))
    print('两数相除的结果：%d'%(sess.run(div)))
    print('两数相除与两数相乘进行相加的结果：%d'%(sess.run(add)))
    print(sess.run(sub))

1000.0
两数相除的结果：10
两数相除与两数相乘进行相加的结果：1010
512


In [18]:
#矩阵运算
import numpy as np
n1 = np.random.randint(0,10,size = (3,2))
n2 = np.random.randint(0,10,size = (2,3))
# m1 = tf.constant()
print(n1,n2)
np.dot(n1,n2)

[[1 3]
 [1 2]
 [1 2]] [[5 6 1]
 [2 7 9]]


array([[11, 27, 28],
       [ 9, 20, 19],
       [ 9, 20, 19]])

In [20]:
tf_n1 = tf.constant(n1,dtype='int32')
tf_n2 = tf.constant(n2,dtype='int32')


matmul = tf.matmul(tf_n1,tf_n2)

with tf.Session() as sess:
    print(sess.run(matmul))

[[11 27 28]
 [ 9 20 19]
 [ 9 20 19]]
