In [1]:
#导入TensorFlow
import tensorflow as tf

In [3]:
# Simple hello world using TensorFlow

# Create a Constant op
# The op is added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.

#定义常量
#使用图(graph)来表示任务 ,最简单的任务：常量
hello = tf.constant('TensorFlow')

python = tf.constant('Python')

number = tf.constant(10)

nd = tf.constant([10,12,19])

f = tf.constant(10.5)


<tf.Tensor 'Const_9:0' shape=() dtype=float32>

In [7]:
session = tf.Session()
session.run(hello).decode('utf-8')


# gu

'TensorFlow'

In [3]:
print(number)

Tensor("Const_2:0", shape=(), dtype=int32)


In [7]:
sess = tf.Session()
print(sess.run(nd))

#任务需要变比
sess.close()

[10 12 19]


In [8]:
sess.run(python)

RuntimeError: Attempted to use a closed Session.

In [9]:
with tf.Session() as sess:
    print(sess.run(number))

10


In [3]:
# Start tf session
#通过tf创建会话，使用session执行操作
sess = tf.Session()

In [5]:
# Run graph
print(sess.run(hello))

#会话执行完任务之后，需要关闭
# sess.close()

b'TensorFlow'


In [6]:
print(sess.run(python))

b'Python'


In [7]:
sess.close()

In [8]:
print(sess.run(python))

RuntimeError: Attempted to use a closed Session.

In [6]:
a = tf.constant(100)
b = tf.

In [7]:
sess.run(a)

100

In [10]:
#声明任务
multy = tf.multiply([1,2,3],[4,5,6])
multy

<tf.Tensor 'Mul:0' shape=(3,) dtype=int32>

In [11]:
with tf.Session() as sess:
    print(sess.run(multy))

[ 4 10 18]


In [12]:
import numpy as np

In [14]:
#mat = matrix
a = tf.constant(np.random.randint(0,10,size = 6),shape = (2,3),dtype='int32')
b = tf.constant(np.random.randint(0,10,size = 6),shape =(3,2),dtype ='int32')

#任务
matmul = tf.matmul(a,b)

In [34]:
data = np.random.randint(0,10,size = (6,3))
print(data)
argmin = tf.arg_max(data,dimension=1)

with tf.Session() as sess:
    print(sess.run(argmin))

[[7 6 1]
 [2 5 0]
 [8 7 3]
 [0 7 1]
 [6 2 5]
 [0 4 8]]
[0 1 0 1 0 2]


[1 1 0]


In [15]:
with tf.Session() as sess:
    print(sess.run(a),sess.run(b))
    
    print(sess.run(matmul))

[[5 4 6]
 [3 2 8]] [[7 7]
 [9 4]
 [7 3]]
[[113  69]
 [ 95  53]]
