In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [22]:
ones = np.ones((5,5))
tf.constant(ones,dtype='float')

<tf.Tensor 'Const_7:0' shape=(5, 5) dtype=float32>

In [16]:
x = np.random.randint(0,100,(5,5))
tf.constant(x)

<tf.Tensor 'Const_3:0' shape=(5, 5) dtype=int64>

In [18]:
y = np.random.randn(3,3)
yy = tf.constant(y)

In [19]:
with tf.Session() as sess:
    print(sess.run(yy))

[[-0.25381228  0.38109785 -0.75075852]
 [-1.17712759 -1.2604375  -0.21270932]
 [-0.37744089  0.53874417 -0.65514836]]


In [14]:
# 常量，数据值
on = tf.constant([[1,2,1],[2,5,9]])

<tf.Tensor 'Const_1:0' shape=(2, 3) dtype=int32>

In [43]:
# 运算
# 占位符
x = tf.placeholder(dtype=tf.int32)
y = tf.placeholder(dtype=tf.int32)

# 任务，修改
# 最小二乘法
# reduce 缩减数据，达到加和的效果
cost = tf.reduce_sum(tf.pow((x-y),2)，)

# graph = tf.add(x,y) + tf.multiply(x,2*y)
# graph

In [45]:
a = np.random.randint(0,10,size = (3,3))
b = np.random.randint(0,10,size = (3,3,))
print(a,b)

[[6 5 1]
 [5 6 3]
 [4 5 9]] [[8 8 5]
 [6 2 1]
 [3 6 3]]


In [44]:
with tf.Session() as sess:
    print(sess.run(cost,feed_dict={x:[2,3,4],y:[6,5,4]}))

20
